language: dart
dart:
  - "stable"
cache:
  directories:
    - $HOME/.pub_cache/
dart_task:
  - test: --platform chrome
  - dartanalyzer: --fatal-warnings lib
  - dartfmt: true
# Fix deploy once Dart is done
# before_deploy:
#   - "cd functions && npm install && cd .."

# deploy:
#   provider: firebase
#   skip_cleanup: true
#   on:
#     branch: "master"
