language: dart
dart:
  - "stable"
dart_task:
  - test: --platform vm
  - test: --platform chrome
  # TODO: Setup coverage
  - dartanalyzer: --fatal-warnings lib
  - dartfmt: --check
# Fix deploy once Dart is done
# before_deploy:
#   - "cd functions && npm install && cd .."

# deploy:
#   provider: firebase
#   skip_cleanup: true
#   on:
#     branch: "master"
