language: node_js
cache: npm
node_js:
  - "11"
script:
  - npm run build
  - npm run test
  - npm run coverage
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ZwzOv/6BK7D84aXBTAVdC0lkEmnPgO7qQrDwL2UTuSDVZyZ1x+ECoIlFkQUY9OHSqJxbd+mn6Pm2vLgEN+McB0fPGpaz06kRdloF6Wzj17TtlMPZqTF1+Us58zqb1dO+bEK3smvK3W7lqbN+GNjrdAirDlKbCk3b/G4naTMivOk0iinqUB355YZGvFxPlscGdviH1PEp9XCCQA40qFucH3oPFS2hRUeI/kZyYpioYgMdDyAwzFhXjIlj8y1VSKQ389BeLgBNXpwWU+ZXRTMaiBvXLcHAmHI69NpdxyzKE4sxcONs9p1eFndQB6q1Vw4jarOQxuM/8TzIepNvTmX4i7sHcA5fRM4gi+xZeOG16ExyqG7TMtDg1sMMis20NABz0Q8/6uWYny97hSWfV9ZP5exw36B6wWQ5vaUY1oZrRdxAmf16SWpyFTF7HIDsVANtAwo+spCUT/aXPNxXAP8SyKCeZ2f/gi3bV8Y7Wt6QQ/HWYJzlV4cNnxqLqIcbn9XcRsT63KXPd7VhPsDVZucgEN+FptTBMzsZ/2X2cOyLoD+jkrWeO3lpeY5216pYr5g8HmU0Hg6jELy/2cxwA0INFnWSVM33t5SBlYyvz8H9iBlhUh/Q5p9ujynQSrsIDgpbXFGH63H8glWEMnpMekwMs+OEe1BsAiFgVMbT6Dnvh30=
  project: bsc-development
  on:
    branch: add-deploy-to-master-step
env:
  global:
    secure: M/HVEz57Nfx+nY6KOGzdJYzJb3eQX7zsTC/i7HNL4F3hXAxQEz1kJuxL/Rz/AJ1xLPM71eyDbnu0goL1cl05NxrxuX1KtjBtroJJnyt6RV4X5dtWqiCpZhQXxClql70Vb3tOZfqls6OgKoCJO8ctRw7rQwLJWu3OgmWKFQ5hxoAwKEeQGfKbYoRRB5uXFinnaTNA+MRSzAMDwJezJa8MARXb6Z+Y44w1tzxbJyDR3S80P2wi0N1oQ5CPdduWsjJb8O2apvzbCF6Br6U02N93MnBHHBpkE7J9RGX21eGXiROwXFr+gsFuHfo8OCCUxZsUkjwnffYkpnKPMCOsrmzWIUcVmSxCRdluuBTwcsWG2UfYdv2ILyggYA2/iWkm2eYmfWL5B/BZUaYtGtDNAOs4x9FTKyxRJknQW5kRk9I+RIy7T7ivZAeSC0TxcoX3Bpriu1Jp44Q0E4va//rvpaKINj4Tw6MNE1V9nM6z8PAHcsVTnS0HdvTNtFofcERFkl0tUPy1SeFE04mS6cWyZKzt8QEonuxTeFAvmT4DgFCh/ATslDKMJ6ITQFNIhaZCrUlCiMLoZLC0IXYhMgeZsir2U9MeulIuKtf4fBaLdLByIOVSSKoGGW5lK95XcWti3FVxqfrf1rSteX+xy5ttz7tcDPp2ljijEz1jppmQLLC7+mc=
