language: node_js
cache: npm
node_js:
  - "11"
script:
  - npm run build
  - npm run test
  - npm run coverage

before_deploy: "npm i eslint -g"

deploy:
  provider: firebase
  edge: true
  skip_cleanup: true
  on:
    branch: "add-deploy-to-master-step"
